# Digilent Basys 3: 100 MHz oscillator, user LEDs LD0..LD15, and switches SW0..SW15.
# Pypeline names the 100 MHz @MAIN clock port clk_100p0.
set_property LOC W5 [get_ports clk_100p0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100p0]

# LEDs
set_property LOC U16 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property LOC E19 [get_ports LD1]
set_property IOSTANDARD LVCMOS33 [get_ports LD1]
set_property LOC U19 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD2]
set_property LOC V19 [get_ports LD3]
set_property IOSTANDARD LVCMOS33 [get_ports LD3]
set_property LOC W18 [get_ports LD4]
set_property IOSTANDARD LVCMOS33 [get_ports LD4]
set_property LOC U15 [get_ports LD5]
set_property IOSTANDARD LVCMOS33 [get_ports LD5]
set_property LOC U14 [get_ports LD6]
set_property IOSTANDARD LVCMOS33 [get_ports LD6]
set_property LOC V14 [get_ports LD7]
set_property IOSTANDARD LVCMOS33 [get_ports LD7]
set_property LOC V13 [get_ports LD8]
set_property IOSTANDARD LVCMOS33 [get_ports LD8]
set_property LOC V3 [get_ports LD9]
set_property IOSTANDARD LVCMOS33 [get_ports LD9]
set_property LOC W3 [get_ports LD10]
set_property IOSTANDARD LVCMOS33 [get_ports LD10]
set_property LOC U3 [get_ports LD11]
set_property IOSTANDARD LVCMOS33 [get_ports LD11]
set_property LOC P3 [get_ports LD12]
set_property IOSTANDARD LVCMOS33 [get_ports LD12]
set_property LOC N3 [get_ports LD13]
set_property IOSTANDARD LVCMOS33 [get_ports LD13]
set_property LOC P1 [get_ports LD14]
set_property IOSTANDARD LVCMOS33 [get_ports LD14]
set_property LOC L1 [get_ports LD15]
set_property IOSTANDARD LVCMOS33 [get_ports LD15]

# Switches
set_property LOC V17 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property LOC V16 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property LOC W16 [get_ports SW2]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property LOC W17 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property LOC W15 [get_ports SW4]
set_property IOSTANDARD LVCMOS33 [get_ports SW4]
set_property LOC V15 [get_ports SW5]
set_property IOSTANDARD LVCMOS33 [get_ports SW5]
set_property LOC W14 [get_ports SW6]
set_property IOSTANDARD LVCMOS33 [get_ports SW6]
set_property LOC W13 [get_ports SW7]
set_property IOSTANDARD LVCMOS33 [get_ports SW7]
set_property LOC V2 [get_ports SW8]
set_property IOSTANDARD LVCMOS33 [get_ports SW8]
set_property LOC T3 [get_ports SW9]
set_property IOSTANDARD LVCMOS33 [get_ports SW9]
set_property LOC T2 [get_ports SW10]
set_property IOSTANDARD LVCMOS33 [get_ports SW10]
set_property LOC R3 [get_ports SW11]
set_property IOSTANDARD LVCMOS33 [get_ports SW11]
set_property LOC W2 [get_ports SW12]
set_property IOSTANDARD LVCMOS33 [get_ports SW12]
set_property LOC U1 [get_ports SW13]
set_property IOSTANDARD LVCMOS33 [get_ports SW13]
set_property LOC T1 [get_ports SW14]
set_property IOSTANDARD LVCMOS33 [get_ports SW14]
set_property LOC R2 [get_ports SW15]
set_property IOSTANDARD LVCMOS33 [get_ports SW15]

# Pushbuttons
set_property LOC U18 [get_ports BTNC]
set_property IOSTANDARD LVCMOS33 [get_ports BTNC]
set_property LOC T18 [get_ports BTNU]
set_property IOSTANDARD LVCMOS33 [get_ports BTNU]
set_property LOC W19 [get_ports BTNL]
set_property IOSTANDARD LVCMOS33 [get_ports BTNL]
set_property LOC T17 [get_ports BTNR]
set_property IOSTANDARD LVCMOS33 [get_ports BTNR]
set_property LOC U17 [get_ports BTND]
set_property IOSTANDARD LVCMOS33 [get_ports BTND]

# Four-digit seven-segment display: digit enables AN0..AN3 and segments CA..CG + DP.
set_property LOC U2 [get_ports AN0]
set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property LOC U4 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property LOC V4 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property LOC W4 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property LOC W7 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property LOC W6 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property LOC U8 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property LOC V8 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property LOC U5 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property LOC V5 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property LOC U7 [get_ports CG]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property LOC V7 [get_ports DP]
set_property IOSTANDARD LVCMOS33 [get_ports DP]

# USB-UART bridge
set_property LOC B18 [get_ports RsRx]
set_property IOSTANDARD LVCMOS33 [get_ports RsRx]
set_property LOC A18 [get_ports RsTx]
set_property IOSTANDARD LVCMOS33 [get_ports RsTx]

# USB HID bridge (PS/2 open-drain clock/data)
set_property LOC C17 [get_ports PS2Clk]
set_property IOSTANDARD LVCMOS33 [get_ports PS2Clk]
set_property PULLUP true [get_ports PS2Clk]
set_property LOC B17 [get_ports PS2Data]
set_property IOSTANDARD LVCMOS33 [get_ports PS2Data]
set_property PULLUP true [get_ports PS2Data]

# Built-in 12-bit VGA resistor DAC
set_property LOC G19 [get_ports VGA_R0]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_R0]
set_property LOC H19 [get_ports VGA_R1]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_R1]
set_property LOC J19 [get_ports VGA_R2]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_R2]
set_property LOC N19 [get_ports VGA_R3]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_R3]
set_property LOC J17 [get_ports VGA_G0]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_G0]
set_property LOC H17 [get_ports VGA_G1]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_G1]
set_property LOC G17 [get_ports VGA_G2]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_G2]
set_property LOC D17 [get_ports VGA_G3]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_G3]
set_property LOC N18 [get_ports VGA_B0]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_B0]
set_property LOC L18 [get_ports VGA_B1]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_B1]
set_property LOC K18 [get_ports VGA_B2]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_B2]
set_property LOC J18 [get_ports VGA_B3]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_B3]
set_property LOC P19 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property LOC R19 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
